name: CD

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: install yarn
        run: npm install -g yarn

      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn export

      - name: set aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: sync dotcom s3 bucket
        run: aws s3 sync ./out s3://dotcom-robinmalgoire
